In [1]:
%pip install numpy

   ---------------------------------------- 0.0/12.3 MB ? eta -:--:--
   ---------------------------------------- 0.0/12.3 MB ? eta -:--:--
   ---- ----------------------------------- 1.3/12.3 MB 7.4 MB/s eta 0:00:02
   --------- ------------------------------ 2.9/12.3 MB 7.3 MB/s eta 0:00:02
   ---------------- ----------------------- 5.0/12.3 MB 8.2 MB/s eta 0:00:01
   -------------------- ------------------- 6.3/12.3 MB 7.6 MB/s eta 0:00:01
   ------------------------ --------------- 7.6/12.3 MB 7.5 MB/s eta 0:00:01
   ------------------------------ --------- 9.4/12.3 MB 7.4 MB/s eta 0:00:01
   ---------------------------------------  12.1/12.3 MB 8.1 MB/s eta 0:00:01
   ---------------------------------------- 12.3/12.3 MB 7.8 MB/s  0:00:01
Note: you may need to restart the kernel to use updated packages.


Python Lists can contain any sort of data types but only 1-Dimensional

In [6]:
import numpy as np

arr= list([1,2,3,4,5])
arr

[1, 2, 3, 4, 5]

In numpy arrays are of 2D, 3D etc.

In [10]:
num_arr= np.array([1,2,3,4,5])
num_arr2= np.array([[1,2,3,4,5],
                    [6,7,8,9,10]])
num_arr3=np.array(
    [[[1,2,3,4,5],
    [6,7,8,9,10],
    [11,12,13,14,15]]]
)

print(num_arr)
print("-------------------")
print(num_arr2)
print("-------------------")
print(num_arr3)

[1 2 3 4 5]
-------------------
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
-------------------
[[[ 1  2  3  4  5]
  [ 6  7  8  9 10]
  [11 12 13 14 15]]]


In [11]:
print(type(num_arr))

<class 'numpy.ndarray'>


size tells us about the number of elements in it

In [14]:
print(num_arr.size)
print(num_arr2.size)
print(num_arr3.size)

5
10
15


shape tells us about the number of rows and columns -> shape(rows,cols)

In [15]:
print(num_arr.shape)
print(num_arr2.shape)
print(num_arr3.shape)

(5,)
(2, 5)
(1, 3, 5)


transpose() just shifts the rows to cols

In [18]:
print(num_arr3.transpose())

[[[ 1]
  [ 6]
  [11]]

 [[ 2]
  [ 7]
  [12]]

 [[ 3]
  [ 8]
  [13]]

 [[ 4]
  [ 9]
  [14]]

 [[ 5]
  [10]
  [15]]]
