In [1]:
import numpy as np

Slicing Ops

In [7]:
x= np.arange(1,51)
x
y=x.reshape(10,5)
y

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35],
       [36, 37, 38, 39, 40],
       [41, 42, 43, 44, 45],
       [46, 47, 48, 49, 50]])

In [9]:
y[0]

array([1, 2, 3, 4, 5])

In [10]:
y[1]

array([ 6,  7,  8,  9, 10])

In [12]:
print(y[0,0])

1


In [16]:
print(y[2,4])

15


In [18]:
print(y[2:5]) # last index 5 not inclusive

[[11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


In [19]:
print(y[0:10])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]
 [26 27 28 29 30]
 [31 32 33 34 35]
 [36 37 38 39 40]
 [41 42 43 44 45]
 [46 47 48 49 50]]


In [22]:
print(y[:10])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]
 [26 27 28 29 30]
 [31 32 33 34 35]
 [36 37 38 39 40]
 [41 42 43 44 45]
 [46 47 48 49 50]]


In [21]:
print(y[3:])

[[16 17 18 19 20]
 [21 22 23 24 25]
 [26 27 28 29 30]
 [31 32 33 34 35]
 [36 37 38 39 40]
 [41 42 43 44 45]
 [46 47 48 49 50]]


In [23]:
print(y[:])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]
 [26 27 28 29 30]
 [31 32 33 34 35]
 [36 37 38 39 40]
 [41 42 43 44 45]
 [46 47 48 49 50]]


In [25]:
print(y[:,2]) # printing only the 2nd column

[ 3  8 13 18 23 28 33 38 43 48]


In [28]:
print(y[1:,3]) # from 1st row till the end but only 3rd col values

[ 9 14 19 24 29 34 39 44 49]


In [33]:
print(y[:,2:5])

[[ 3  4  5]
 [ 8  9 10]
 [13 14 15]
 [18 19 20]
 [23 24 25]
 [28 29 30]
 [33 34 35]
 [38 39 40]
 [43 44 45]
 [48 49 50]]
