np.arange(start,end,step) will return a numpy array from the start index to the end index(not inclusive)

In [2]:
import numpy as np

w=np.arange(1,10)
x=np.arange(1,20,2)
print(w)
print(x)

[1 2 3 4 5 6 7 8 9]
[ 1  3  5  7  9 11 13 15 17 19]


reshape((rows,cols)) takes the a numpy array and spreads the values across the given rows and cols

In [10]:
print(w.shape) # 9 cols and 1 row
reshape_w=w.reshape(3,3)
print(w.reshape((3,3))) # the same array now spread across 3 rows and 3 cols

(9,)
[[1 2 3]
 [4 5 6]
 [7 8 9]]


flatten() and ravel() takes it back to a 1D array. Single row and multiple cols

In [13]:
reshape_w.flatten()
reshape_w.ravel()

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

ravel(): it does the changes in place. That is the output is a reference of the original array. So all modifications done are on the original array. ravel() is faster as it does not occupy any memory. It is a library level function

flatten(): it creates a copy of the array and makes the changes. So the original array is not modified. Slower than ravel as it occupies new memory. It is a method of the ndarray object