In [1]:
import numpy as np

Gives me floating point 3 rows and 3 cols 2D array of type float with random numbers generated in it

In [2]:
np.empty((3,3), dtype=float)

array([[6.23042070e-307, 4.67296746e-307, 1.69121096e-306],
       [1.89146047e-307, 6.23047163e-307, 2.22526399e-307],
       [6.23053614e-307, 7.56592338e-307, 5.33590898e-322]])

np.ones((rows,cols), dtype=int) Gives an numpy array of ones. Default is float

In [6]:
np.ones((2,2), dtype=int)

array([[1, 1],
       [1, 1]])

np.zeros((rows,cols),dtype=int) Gives a numpy array of zeros. Default is float

In [8]:
np.zeros((3,3), dtype=int)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])